
- name: push docker image to AWS ECR Sample
  hosts: local
  tasks:
    - name: make aws directory
      file:
        dest: ~/.aws
        state: directory
        mode: u=rwx,g=,o=

    - name: copy aws config
      template:
        src: aws/config
        dest: ~/.aws/config
        mode: u=rw,g=,o=

    - name: copy aws credentials
      template:
        src: aws/credentials
        dest: ~/.aws/credentials
        mode: u=rw,g=,o=

    - name: install docker-py for build docker
      pip:
        name: boto3
        state: present

    - name: build docker image
      docker_image: 
        path: ./
        name: "{{ Shaji1 }}"
        tag: "{{ Shaji1 }}"

    - name: docker login (must `--no-include-email`)
      shell: "$(aws ecr get-login  --Region {{ us-east1 }} --no-include-email)"
      args:
        executable: /bin/bash

    - name: install boto3
      pip:
        name: boto3
        state: present

    - name: create repository
      ecs_ecr:
        name: "{{ shaji }}"
        aws_access_key: "{{ AKIAJPOJYO4GYDQJBMTA}}"
        aws_secret_key: "{{ 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 }}"
        region: "{{ us-east1 }}"
      register: ecr_repo

    - name: add tag
      docker_image:
        name: "{{ shaji1 }}:{{ image_version }}"
        repository: "{{ 765421969562.dkr.ecr.us-east-1.amazonaws.com/shaji1 }}"
        tag: "{{ 765421969562.dkr.ecr.us-east-1.amazonaws.com/shaji1 }}:{{ image_version }}"

    - name: push image to ecr
      docker_image:
        name: "{{ 765421969562.dkr.ecr.us-east-1.amazonaws.com/shaji1 }}:{{ image_version }}"
        push: yes
